### ISSUE TITLE
Враћање сајта назад.

### ISSUE THREAD

**Issue by lazanet** [esveske/esveske.github.io#2]
Дисклејер за почетак: Савана сам упознао 2010. године на ЛНШ-у и након тога сам (нажалост) имао прилике да 3 пута пролазим кроз пакао прегледања рада код њега. Ако је мени било толико грозно, могу мислити како је тек било девојкама које су пролазиле кроз много горе ствари. Захвалан сам мојим менторима на семинару ПФЕ што су се (иако нису знали за конкретне случајеве недела) заиста трудили да минимизују време које проводимо тамо јер су знали да је тежак и да никоме није пријатно поред њега.

-----

Петничке свеске престављају продукт скоро две деценије научног процеса младих људи у Србији. Нисам упознао особу која је објавила рад у свесци а да на то није поносна. Овај репозиторијум је био феноменалан као место где мош линковати на оно шта си радио док си био средњошколац, а што је неретко значајно квалитетније него већина дипломских (и неких мастер) радова на факултетима. Сад мош линковати на 404 (а нико не воли да меће мртве линкове у CV).

Највећи злочинац у историји човечанства - неки аустријанац са брчићима - је објавио у затвору књигу која представља његов аутобиографски манифест. Након тога је - баш вођен идејама из те књиге - покренуо најгрознији злочиначки подухват у историји човечанства. Његова књига се (са јаким фуснотама на свакој страници) и даље продаје. Ова аналогија чак и не пије воду будући да Саван чак није аутор радова, већ је само радио рецензије и слагање текста.

Боља аналогија био би Харви Вајнстин, амерички продуцент који правоснажно осуђен на 23 године робије због сексуалних напада на глумице. То ни близу није значило да ћемо побрисати све Тарантинове филмове у чијој је изради дотични учествовао.

Сматрам да је најбоље решење за овај репозиторијум враћање сајта на пређашње стање и додавање напомена свуда где се осуђује понашање дотичног и управе, и оставља линк на форму где би жртве дотичног (уколико то баш желе) могле да затраже брисање својих радова. То - по мени - представља добар баланс између протеста и утилитаризма.

Тренутно стање ми - искрено - делује врло бесмислено - јер заиста не помаже никоме. Уколико горепоменуто решење није прихватљиво, ја ћу кад стигнем или спиновати свој fork где ћу статично хостовати `25b957f9bbf09a56cdb86c28dbedc7172438f366`, или ћу садржину истог комита дамповати на arxiv.org или неки сличан сајт. 

Где видим бољи простор за активизам по питању расветљавања случајева сексуалних деликата у станици јесте рецимо интерна истрага унутар семинара рачунарства поводом [овога](https://imgur.com/a/fLwGfrV), о чему се већ неко време шушка, али нисам видео да је неко нешто званично предузео.

cc: @profMagija

**Comment by profMagija** [comment]
sajt je sklonjen sa vrlo jednostavnim razlogom, ne jer ja "kaznim" nekoga ili želim da "obrišem radove". kao neko čiji rad je tamo i ko je pre bukvalno 4 dana imao intervju za posao na kom su mu rekli "e hteo sam da pročitam ali jbg 404 je", razumem taj bol.

sajt će biti vraćen čim se situacija definitivno smiri. Ako hoćeš detalje, piši mi na mejl, jer ne bih javno.

molim te nemoj iz istog razloga hostovati taj sajt. ako nekome treba neki rad može sajt naći i na weyback machine.
